version: "3.7"
services:
  db:
    image: postgres
    container_name: db    
    environment:
      - POSTGRES_DB=guru
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - TZ=GMT
    restart: always    
    ports:
      - "5432:5432"